name: firebase_dynamic_links_example
description: Demonstrates how to use the firebase_dynamic_links plugin.

dependencies:
  flutter:
    sdk: flutter

  firebase_dynamic_links:
    path: ../
  firebase_core: ^0.4.0

  url_launcher: ^4.2.0

flutter:
  uses-material-design: true
